const $ = (id) => document.getElementById(id);
let state, library;
const active = () => state?.tabs.find((tab) => tab.id === state.activeId);
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[char]);
function render(next) {
  state = next; const tab = active();
  $('tabs').innerHTML = state.tabs.map((item) => '<div class="tab '+(item.active?'active':'')+'" data-id="'+item.id+'">'+(item.favicon?'<img src="'+escapeHtml(item.favicon)+'">':'<span class="fallback">◇</span>')+'<span class="tab-title">'+escapeHtml(item.title||'New Tab')+'</span>'+(item.suspended&&item.url!=='clearweb://newtab'?'<span class="sleep">sleep</span>':'')+'<button class="tab-close">×</button></div>').join('');
  $('url').value = tab?.url === 'clearweb://newtab' ? '' : tab?.url || ''; $('newtab').classList.toggle('hidden', tab?.url !== 'clearweb://newtab');
  $('back').classList.toggle('disabled', !state.canGoBack); $('forward').classList.toggle('disabled', !state.canGoForward); $('clean').classList.toggle('active', state.settings.cleanWeb); document.querySelector('.ai-pill').textContent = state.settings.aiEnabled ? 'AI ON' : 'AI OFF';
  document.querySelectorAll('.tab').forEach((element) => { element.onclick=()=>window.clearweb.activateTab(element.dataset.id); element.querySelector('.tab-close').onclick=(event)=>{event.stopPropagation();window.clearweb.closeTab(element.dataset.id)}; });
}
const navigate = (value) => window.clearweb.navigate(value);
$('nav').onsubmit=(e)=>{e.preventDefault();navigate($('url').value)}; $('hero-search').onsubmit=(e)=>{e.preventDefault();navigate($('hero-input').value)};
$('new-tab').onclick=()=>window.clearweb.newTab(); $('back').onclick=()=>window.clearweb.back(); $('forward').onclick=()=>window.clearweb.forward(); $('reload').onclick=()=>window.clearweb.reload(); $('home').onclick=()=>window.clearweb.home(); $('bookmark').onclick=()=>window.clearweb.toggleBookmark();
function closePanel(){ $('panel').classList.add('hidden'); $('scrim').classList.add('hidden'); }
$('panel-close').onclick=closePanel; $('scrim').onclick=closePanel;
function openPanel(kicker,title,html){ $('panel-kicker').textContent=kicker; $('panel-title').textContent=title; $('panel-body').innerHTML=html; $('panel').classList.remove('hidden'); $('scrim').classList.remove('hidden'); }
$('protection').onclick=()=>{ openPanel('Clearweb protection','Protection dashboard','<div class="stat-grid"><div class="stat"><strong>'+state.protection.blocked+'</strong><span>ads & trackers blocked</span></div><div class="stat"><strong>'+state.protection.trackingParamsRemoved+'</strong><span>tracking parameters removed</span></div></div><div class="toggle-row"><div><b>Clean Web</b><div class="muted">Hide clutter and stop autoplay</div></div><button id="toggle-clean" class="toggle '+(state.settings.cleanWeb?'on':'')+'"></button></div><div class="toggle-row"><div><b>Local AI</b><div class="muted">Qwen semantic assistant</div></div><button id="toggle-ai" class="toggle '+(state.settings.aiEnabled?'on':'')+'"></button></div><p class="muted">Blocking stays deterministic and fast. AI never sits on the network path. Failures never prevent pages loading.</p>'); $('toggle-clean').onclick=()=>window.clearweb.setSettings({cleanWeb:!state.settings.cleanWeb}); $('toggle-ai').onclick=()=>window.clearweb.setSettings({aiEnabled:!state.settings.aiEnabled}); };
$('clean').onclick=()=>window.clearweb.setSettings({cleanWeb:!state.settings.cleanWeb});
$('assistant').onclick=()=>{ openPanel('AI assistant','Ask the current page','<div class="ai-status"><span class="dot"></span><div><b>Qwen · Local 🔒</b><div class="muted">'+escapeHtml(state.provider.model)+' via Ollama</div></div></div><div class="quick-actions"><button data-prompt="Summarize this page in five concise bullets.">Summarize</button><button data-prompt="Explain the main idea of this page simply.">Explain</button></div><textarea id="prompt" placeholder="Ask anything about this page…"></textarea><button id="ask" class="primary">Ask local Qwen</button><div id="answer"></div>'); document.querySelectorAll('[data-prompt]').forEach((b)=>b.onclick=()=>{$('prompt').value=b.dataset.prompt;ask()}); $('ask').onclick=ask; };
async function ask(){ const prompt=$('prompt').value.trim(); if(!prompt)return; $('answer').innerHTML='<div class="answer muted">Reading page and asking local Qwen…</div>'; $('ask').disabled=true; const pageText=await window.clearweb.extractPage(); const result=await window.clearweb.askAI({prompt,pageText}); $('answer').innerHTML='<div class="answer">'+escapeHtml(result.ok?result.text:[result.error,result.hint].filter(Boolean).join('\n\n'))+'</div>'; $('ask').disabled=false; }
async function showLibrary(tab='history'){ library=await window.clearweb.getLibrary(); const labels=['history','bookmarks','downloads','sessions']; openPanel('Your browser','Library','<div class="list-tabs">'+labels.map((x)=>'<button data-lib="'+x+'" class="'+(x===tab?'active':'')+'">'+x[0].toUpperCase()+x.slice(1)+'</button>').join('')+'</div><div id="lib-list"></div>'); document.querySelectorAll('[data-lib]').forEach((b)=>b.onclick=()=>showLibrary(b.dataset.lib)); const items=library[tab]||[]; $('lib-list').innerHTML=items.length?items.slice(0,150).map((item)=>'<div class="item"><b>'+escapeHtml(item.title||item.filename||item.name||item.url)+'</b><small>'+escapeHtml(item.url||new Date(item.createdAt||item.visitedAt||item.startedAt).toLocaleString())+'</small>'+(tab==='downloads'&&item.path?'<button data-open="'+escapeHtml(item.path)+'">Open</button>':'')+(tab==='sessions'?'<button data-restore="'+item.id+'">Restore</button>':'')+'</div>').join(''):'<p class="muted">Nothing here yet.</p>'; if(tab==='sessions')$('lib-list').insertAdjacentHTML('afterbegin','<button id="save-session" class="primary">Save current session</button>'); if($('save-session'))$('save-session').onclick=async()=>{await window.clearweb.saveSession();showLibrary('sessions')}; document.querySelectorAll('[data-restore]').forEach((b)=>b.onclick=()=>window.clearweb.restoreSession(b.dataset.restore)); document.querySelectorAll('[data-open]').forEach((b)=>b.onclick=()=>window.clearweb.openDownload(b.dataset.open)); }
$('library').onclick=()=>showLibrary(); window.clearweb.onState(render); window.clearweb.onDownloads(()=>{}); window.clearweb.getState().then(render);
document.addEventListener('keydown',(e)=>{ if(e.metaKey&&e.key.toLowerCase()==='l'){e.preventDefault();$('url').focus();$('url').select()} if(e.metaKey&&e.key.toLowerCase()==='t'){e.preventDefault();window.clearweb.newTab()} if(e.metaKey&&e.key.toLowerCase()==='w'){e.preventDefault();const tab=active();if(tab)window.clearweb.closeTab(tab.id)} });
