const $ = (id) => document.getElementById(id);
let state, library;
const active = () => state?.tabs.find((tab) => tab.id === state.activeId);
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[char]);
function render(next) {
  state = next; const tab = active();
  const tabs = $('tabs'); const seen = new Set();
  state.tabs.forEach((item, index) => {
    seen.add(item.id); let element = tabs.querySelector(`[data-id="${CSS.escape(item.id)}"]`);
    if (!element) { element = document.createElement('div'); element.className='tab'; element.dataset.id=item.id; element.innerHTML='<span class="fallback">◇</span><img hidden><span class="tab-title"></span><span class="tab-status"></span><button class="tab-close">×</button>'; element.onclick=()=>window.clearweb.activateTab(element.dataset.id); element.querySelector('.tab-close').onclick=(event)=>{event.stopPropagation();window.clearweb.closeTab(element.dataset.id)}; }
    element.classList.toggle('active', item.active); element.querySelector('.tab-title').textContent=item.title||'New Tab';
    const image=element.querySelector('img'); const fallback=element.querySelector('.fallback'); image.hidden=!item.favicon; fallback.hidden=Boolean(item.favicon); if(item.favicon&&image.src!==item.favicon) image.src=item.favicon;
    const status=element.querySelector('.tab-status'); status.className=item.loading?'tab-status tab-loading':item.suspended&&item.url!=='clearweb://newtab'?'tab-status sleep':'tab-status'; status.textContent=item.loading?'◌':item.suspended&&item.url!=='clearweb://newtab'?'sleep':'';
    const current=tabs.children[index]; if(current!==element) tabs.insertBefore(element,current||null);
  });
  Array.from(tabs.children).forEach((element)=>{if(!seen.has(element.dataset.id))element.remove()});
  $('url').value = tab?.url === 'clearweb://newtab' ? '' : tab?.url || ''; $('newtab').classList.toggle('hidden', tab?.url !== 'clearweb://newtab');
  $('back').classList.toggle('disabled', !state.canGoBack); $('forward').classList.toggle('disabled', !state.canGoForward); $('clean').classList.toggle('active', state.settings.cleanWeb); document.querySelector('.ai-pill').textContent = state.settings.aiEnabled ? 'AI ON' : 'AI OFF';
  $('bookmark').textContent = state.bookmarked ? '★' : '☆'; $('bookmark').title = state.bookmarked ? 'Remove bookmark' : 'Bookmark this page';
}
const navigate = (value) => window.clearweb.navigate(value);
$('nav').onsubmit=(e)=>{e.preventDefault();navigate($('url').value)}; $('hero-search').onsubmit=(e)=>{e.preventDefault();navigate($('hero-input').value)};
$('new-tab').onclick=()=>window.clearweb.newTab(); $('back').onclick=()=>window.clearweb.back(); $('forward').onclick=()=>window.clearweb.forward(); $('reload').onclick=()=>window.clearweb.reload(); $('home').onclick=()=>window.clearweb.home(); $('bookmark').onclick=()=>window.clearweb.toggleBookmark();
function closePanel(){ $('panel').classList.add('hidden'); $('scrim').classList.add('hidden'); window.clearweb.setPanelOpen(false); }
$('panel-close').onclick=closePanel; $('scrim').onclick=closePanel;
function openPanel(kicker,title,html){ $('panel-kicker').textContent=kicker; $('panel-title').textContent=title; $('panel-body').innerHTML=html; $('panel').classList.remove('hidden'); $('scrim').classList.remove('hidden'); window.clearweb.setPanelOpen(true); }
$('protection').onclick=()=>{ openPanel('Clearweb protection','Protection dashboard','<div class="stat-grid"><button id="blocked-stat" class="stat expandable"><strong>'+state.protection.blocked+'</strong><span>ads & trackers blocked · view details</span></button><div class="stat"><strong>'+state.protection.trackingParamsRemoved+'</strong><span>tracking parameters removed</span></div></div><div id="blocked-details" class="hidden"></div><div class="toggle-row"><div><b>Clean Web</b><div class="muted">Hide clutter and stop autoplay</div></div><button id="toggle-clean" class="toggle '+(state.settings.cleanWeb?'on':'')+'"></button></div><div class="toggle-row"><div><b>Local AI</b><div class="muted">Qwen semantic assistant</div></div><button id="toggle-ai" class="toggle '+(state.settings.aiEnabled?'on':'')+'"></button></div><p class="muted">Blocking stays deterministic and fast. AI never sits on the network path. Failures never prevent pages loading.</p>'); $('blocked-stat').onclick=showBlockedDetails; $('toggle-clean').onclick=()=>window.clearweb.setSettings({cleanWeb:!state.settings.cleanWeb}); $('toggle-ai').onclick=()=>window.clearweb.setSettings({aiEnabled:!state.settings.aiEnabled}); };
async function showBlockedDetails(){ const box=$('blocked-details'); if(!box)return; if(!box.classList.contains('hidden')){box.classList.add('hidden');return;} box.classList.remove('hidden');box.innerHTML='<p class="muted">Loading blocked requests…</p>';const items=await window.clearweb.getProtectionDetails();box.innerHTML='<div class="blocked-list">'+(items.length?items.map((item)=>'<div class="blocked-row"><b>'+escapeHtml(item.host||item.url||'Unknown host')+'</b><small>'+escapeHtml(item.type+' · from '+(item.source||'this page'))+'</small><small title="'+escapeHtml(item.url)+'">'+escapeHtml(item.url)+'</small></div>').join(''):'<p class="muted">No request details recorded in this session yet.</p>')+'</div>';}
$('clean').onclick=()=>window.clearweb.setSettings({cleanWeb:!state.settings.cleanWeb});
$('ai-clean').onclick=async()=>{openPanel('AI page cleaner','Cleaning this page…','<div class="ai-status"><span class="dot"></span><div><b>Qwen is reviewing page structure</b><div class="muted">The page remains usable while local AI identifies ad containers.</div></div></div><div id="clean-result" class="answer muted">Finding advertisements and empty placeholders…</div>');const result=await window.clearweb.cleanWithAI();const box=$('clean-result');if(box){box.classList.remove('muted');box.textContent=result.ok?result.text:[result.error,result.hint].filter(Boolean).join('\n\n');}};
$('assistant').onclick=()=>{ openPanel('AI assistant','Ask anything','<div class="ai-status"><span class="dot"></span><div><b>Qwen · Local 🔒</b><div class="muted">'+escapeHtml(state.provider.model)+' via Ollama</div></div></div><div class="quick-actions"><button data-page-prompt="Summarize this page in five concise bullets.">Summarize page</button><button data-page-prompt="Explain the main idea of this page simply.">Explain page</button></div><label class="context-option"><input id="use-page" type="checkbox"> Use current page as context</label><textarea id="prompt" placeholder="Ask about weather, ideas, writing, code—or this page…"></textarea><button id="ask" class="primary">Ask local Qwen</button><div id="answer"></div>'); document.querySelectorAll('[data-page-prompt]').forEach((b)=>b.onclick=()=>{$('prompt').value=b.dataset.pagePrompt;$('use-page').checked=true;ask()}); $('ask').onclick=ask; };
async function ask(){ const prompt=$('prompt').value.trim(); if(!prompt)return; const usePage=$('use-page').checked; $('answer').innerHTML='<div class="answer muted">'+(usePage?'Reading this page and asking local Qwen…':'Asking local Qwen…')+'</div>'; $('ask').disabled=true; const pageText=usePage?await window.clearweb.extractPage():''; const result=await window.clearweb.askAI({prompt,pageText}); $('answer').innerHTML='<div class="answer">'+escapeHtml(result.ok?result.text:[result.error,result.hint].filter(Boolean).join('\n\n'))+'</div>'; $('ask').disabled=false; }
async function showLibrary(tab='history'){ library=await window.clearweb.getLibrary(); const labels=['history','bookmarks','downloads','sessions']; openPanel('Your browser','Library','<div class="list-tabs">'+labels.map((x)=>'<button data-lib="'+x+'" class="'+(x===tab?'active':'')+'">'+x[0].toUpperCase()+x.slice(1)+'</button>').join('')+'</div><div id="lib-list"></div>'); document.querySelectorAll('[data-lib]').forEach((b)=>b.onclick=()=>showLibrary(b.dataset.lib)); const items=library[tab]||[]; $('lib-list').innerHTML=items.length?items.slice(0,150).map((item)=>'<div class="item"><b>'+escapeHtml(item.title||item.filename||item.name||item.url)+'</b><small>'+escapeHtml(item.url||new Date(item.createdAt||item.visitedAt||item.startedAt).toLocaleString())+'</small>'+(tab==='downloads'&&item.path?'<button data-open="'+escapeHtml(item.path)+'">Open</button>':'')+(tab==='sessions'?'<button data-restore="'+item.id+'">Restore</button>':'')+'</div>').join(''):'<p class="muted">Nothing here yet.</p>'; if(tab==='sessions')$('lib-list').insertAdjacentHTML('afterbegin','<button id="save-session" class="primary">Save current session</button>'); if($('save-session'))$('save-session').onclick=async()=>{await window.clearweb.saveSession();showLibrary('sessions')}; document.querySelectorAll('[data-restore]').forEach((b)=>b.onclick=()=>window.clearweb.restoreSession(b.dataset.restore)); document.querySelectorAll('[data-open]').forEach((b)=>b.onclick=()=>window.clearweb.openDownload(b.dataset.open)); }
$('library').onclick=()=>showLibrary(); window.clearweb.onState(render); window.clearweb.onProtection((protection)=>{ if(!state)return; state.protection=protection; const stats=document.querySelectorAll('.stat strong'); if(stats.length===2){stats[0].textContent=protection.blocked;stats[1].textContent=protection.trackingParamsRemoved;} }); window.clearweb.onSiteCompatibility((info)=>{openPanel('Site compatibility',info.site,'<div class="answer">'+escapeHtml(info.message)+'</div><button id="open-compatible" class="primary">Open in Chrome</button>');$('open-compatible').onclick=()=>window.clearweb.openExternalSite(info.url);}); window.clearweb.onDownloads(()=>{}); window.clearweb.getState().then(render);
document.addEventListener('keydown',(e)=>{ if(e.metaKey&&e.key.toLowerCase()==='l'){e.preventDefault();$('url').focus();$('url').select()} if(e.metaKey&&e.key.toLowerCase()==='t'){e.preventDefault();window.clearweb.newTab()} if(e.metaKey&&e.key.toLowerCase()==='w'){e.preventDefault();const tab=active();if(tab)window.clearweb.closeTab(tab.id)} });
